/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_test_FileUtils */

#include <stdio.h>

#ifndef _Included_com_ndk_test_FileUtils
#define _Included_com_ndk_test_FileUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndk_test_FileUtils
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_ndk_test_FileUtils_diff
  (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
